### ISSUE TITLE
Documentation is not visible after deployment

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/artillery#11]
Using docsify I have initialized the documentation under the docs. But it is not visible under bastion.rs.
Most probably artillery.bastion.rs would be the best domain to land to the documentation.

Currently, it is not visible. Let's make it visible :)

**Comment by o0Ignition0o** [comment]
https://artillery.bastion.rs there you go!

**Comment by Kerollmops** [comment]
Hey, I see that you are building some documentation for artillery with docsify.

Just to make sure that you are aware of the alternatives to docsify, at [MeiliSearch](https://docs.meilisearch.com/guides/) we moved form docsify to vuepress instead, it is way better in many ways.

I will let you juge by yourself and I'll continue to keep a look at artillery.

**Comment by vertexclique** [comment]
@Kerollmops Thanks for the suggestion! I've just gazed on that. I will move to vuepress.

**Comment by vertexclique** [comment]
Closing this because deployment is done. Opened #13
