### ISSUE TITLE
Get frequent SuspectedDown on localhost

### ISSUE THREAD

**Issue by mosuka** [bastion-rs/artillery#48]
* **Version**: artillery-core = "0.1.2-alpha.3"
* **Platform**: Linux tpx1cg9 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

I am building an application using artillery-core by referring to the sample here.

https://github.com/bastion-rs/artillery/blob/master/artillery-core/examples/cball_infection.rs

I have successfully brought up a three-node cluster, but when I start the third node, I get frequent `SuspectedDown`.
Even with a two-node cluster, there is no problem in the beginning, but after a few minutes, the `SuspectedDown` may occur.
What can I do to solve this problem?

**Comment by fulmicoton** [comment]
The following code is suspicious. 
https://github.com/bastion-rs/artillery/blob/master/artillery-core/src/epidemic/state.rs#L265-L269

```
        let (remaining, expired): (Vec<_>, Vec<_>) = self
            .pending_responses
            .iter()
            .cloned()
            .partition(|&(t, _, _)| t < now);
```

Shouldn't it be the opposite?
An expired element is one for which (now>deadline), which is the second argumnet.

Aren't expired and remaining inverted.

**Comment by fulmicoton** [comment]
Is there a plan to publish the crate?
