### ISSUE TITLE
Epidemic peer should be able to send payload to another peer

### ISSUE THREAD

**Issue by poonai** [bastion-rs/artillery#6]
**Is your feature request related to a problem? Please describe.**
Right now, the peer knows only how many peers are alive and dead. But, there is no way to get details of the peer. So, we should support a way to send a message to the peer. 

My use-case:
My peer listening on two ports. One is by the epidemic and another one is grpc server. All my application logic is on the grpc server. So, I need a way to communicate with my peers to get the information that I want. 

**How this feature helps me?**

As soon I get an alive event, I'll ask for the required details which I want. Then the receiver peer will respond to my question. 

 
**Describe the solution you'd like**
I need cluster.send_payload method which takes destination peer id and payload as a parameter and sends the payload to the destination peer.

**Comment by vertexclique** [comment]
Closed by #8
